[package]
name = "exporter"
version = "0.1.0"
authors = ["Leo Adamek <leo@adamek.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iracing = "0.2.6"